version: '3.8'

services:
  givi-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../saved_models:/app/saved_models
      - ../data:/app/data
    environment:
      - DEBUG=false
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: givi_db
      POSTGRES_USER: givi_user
      POSTGRES_PASSWORD: givi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
